### ISSUE TITLE
[IBMMQ] Add a sample to configure multiple query managers in the docs

### ISSUE THREAD

**Issue by marcsanmi** [newrelic/newrelic-prometheus-exporters-packages#105]
We don't have documented how multiple query managers can be configured. As an example:

```integrations:
  - name: nri-ibmmq
    config:
      hostname: localhost
      port: 1414
      queue_manager: QM1
      channel: SYSTEM.DEF.SVRCONN
      username: your_mq_user
      password: your_mq_password
      monitored_queues: '!SYSTEM.*,*'
      monitored_channels: '*'
      monitored_topics: '*'
      monitored_subscriptions: '*'
      exporter_port: 9157
  - name: nri-ibmmq
    config:
      hostname: localhost
      port: 1414
      queue_manager: QM2
      channel: SYSTEM.DEF.SVRCONN
      username: your_mq_user
      password: your_mq_password
      monitored_queues: '!SYSTEM.*,*'
      monitored_channels: '*'
      monitored_topics: '*'
      monitored_subscriptions: '*'
      exporter_port: 9158 
```

We should add a warning note reflecting in a way like `This approach should be used carefully as for each instance we will spawn an exporter and a nri-prometheus`.

**Comment by carlossscastro** [comment]
Related to IBM MQ documentation we should also move the samples to the "Configure the Integration" section.

Also the "IBM MQ instance settings" should be moved to the same section:
https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/ibmmq-monitoring-integration/#instance-settings

This is to align the docs with other integration docs
