### ISSUE TITLE
[IBBMQ] stdout of exporter printed as payload error.

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-prometheus-exporters-packages#108]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
The ibmmq exporter prints some lines to `stdout` which are treated as integration payload by the Agent failing to parse it and logging some warning messages that leads to miss interpretation and confusion.

## Steps to Reproduce
This happens every time the integration runs for first time 

## Expected Behavior
These lines should be treated as logs, not payload.

Possible solutions:
- Ideally the exporter should not print anything on stdout. We could make a PR on the exporter to fix this.
- Add a mechanism to the Agent to recognize that the exporter is not an integration so stdout should not be treated as payload.

## Relevant Logs / Console output

```
 level=warning msg="Cannot emit integration payload" cfg_protocol_name=cfg-nri-ibmmq component=integrations.runner.Runner error="invalid character 'B' looking for beginning of value" integration_name=ibmmq-exporter parent_integration_name=nri-ibmmq payload="Build Platform: Linux/x86_64" runner_uid=x
 level=warning msg="error retrieving integration protocol version" cfg_protocol_name=cfg-nri-ibmmq component=integrations.emitter.Emitter error="no content to parse" integration_name=ibmmq-exporter parent_integration_name=nri-ibmmq
```

**Comment by paologallinaharbur** [comment]
There is only this line printing to stdout 
https://github.com/ibm-messaging/mq-metric-samples/blob/e4bd468a828f6ddcf3d6055647d0b5a0b2fccc25/pkg/config/config.go#L378

I'll open a PR to fix that, but I fear that changing it to stdErr can be too opinionated
