### ISSUE TITLE
[aerospike] exporter config file path not mapped to config file

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-prometheus-exporters-packages#174]
Config file location is fixed in the [mapping files ](https://github.com/newrelic/newrelic-prometheus-exporters-packages/blob/main/exporters/aerospike/aerospike.json.tmpl#L6) even though its an exposed configuration parameter on the [config sample](https://github.com/newrelic/newrelic-prometheus-exporters-packages/blob/main/exporters/aerospike/aerospike-config.yml.sample#L18).

Mapping should leverage `{{.exporter_files_path}}` as explained in the [doc](https://github.com/newrelic/newrelic-prometheus-exporters-packages#adding-external-config-files).

**Comment by pkosanam** [comment]
Thank you @gsanchezgavier , I have created a PR on this issue.

PR: https://github.com/newrelic/newrelic-prometheus-exporters-packages/pull/180

Could you please do the needful.

Thank you 😃
