### ISSUE TITLE
NRI MongoDB3 Integration- MongoDB exporter not collecting some attributes correctly.

### ISSUE THREAD

**Issue by sauharda1** [newrelic/newrelic-prometheus-exporters-packages#219]
### **Issue** Title: Incomplete Metrics and Missing Cluster ID in MongoDB Exporter for New Relic Integration

Description:
We have installed MongoDB exporter using the image percona/mongodb_exporter in our EKS cluster which is running on v1.25. We also have NRI bundle installed via helm chart. NRI bundle includes the infrastructure agent as well as newrelic-prometheus-agent.
Most of the metrics and attributes seem to be fine except the mongoDB cluster_id for now. It looks like the MongoDB exporter is not collecting it properly. 

### **Environment:**

   Exporter Version: v0.39.0
   MongoDB Atlas Version: MongoDB 5
   New Relic Integration Bundle: Helm Chart- 5.0.42

### **Issue:**
The mongoDB cluster_id doesn't look to be correct. Currently, it shows cluster_id to be 000000000 which is incorrect. Also the transactions and the related metrics to it are also not fetching. Please refer to the screenshots.

### **Expected Behavior:**
- It should collect all the metrics of the MongoDB 5
- It also needs to populate the cluster_id correctly.

### **Configuration Files:**
**Below is the code for NRI bundle values.yaml**
```

> 
>  `nri-bundle:
> 
>   newrelic-infrastructure:
>     enabled: true
>     integrations:
>        mongodb3-config.yml: 
>           integrations: 
>             - name: nri-mongodb3
>               config:
>                 mongodb_cluster_name: clustername
>                 mongodb_uri: "mongodb+srv://user:password@cluster_name_removed?retryWrites=true&writeConcern=majority"
>                 exporter_port: 9126
>       
>   nri-metadata-injection:
>     enabled: true
>   
>   kube-state-metrics:
>     enabled: true
>   
>   nri-kube-events:
>     enabled: true
>   
>   newrelic-logging:
>     enabled: true

>   global:
>     cluster: removed
>     licenseKey: removed 
> 
>   nri-prometheus:
>     enabled: true
> 
>   newrelic-prometheus-agent:
>     enabled: true
>     config:
>       kubernetes:
>         jobs:
>         - job_name_prefix: mongodb-exporter
>           integrations_filter:
>             enabled: false
>           target_discovery:
>             pod: true
>             endpoints: true
>             filter:
>               annotations:
>           # <string>: <regex>
>                 prometheus.io/scrape: true
>                 prometheus.io/port: "metrics"
>                 newrelic.io/scrape: "true"
>           image: newrelic/nri-mongodb3:3.0.1
>       common:
>         external_labels:
>           cluster_name: removed
>           mongodb_cluster_name: removed `
```

**Below is the exporter values.yaml**

```
> `mongodb: 
>   uri: "mongodb+srv://user:pass@cluster_name_removed?retryWrites=true&writeConcern=majority"
> 
> extraArgs:
>   - '--no-mongodb.direct-connect'
>   - --collect-all
>   - --discovering-mode
> 
> metrics:
>   enabled: true
>   extraFlags: "--collect-all --discovering-mode=true"
> 
> port: "9126"`
```

**### SCREENSHOT**
Below are the 2 images of the defects we have encountered. One for the cluster_id and another of the transactions and transactions latency.

1. 
<img width="812" alt="Screenshot 2023-11-27 at 11 19 39 AM" src="https://github.com/newrelic/newrelic-prometheus-exporters-packages/assets/120621773/17464ee9-c07b-4ddd-92c5-4b9a5529d03b">

**2.**

<img width="704" alt="Screenshot 2023-11-27 at 11 29 01 AM" src="https://github.com/newrelic/newrelic-prometheus-exporters-packages/assets/120621773/ffe4c58f-83d1-4146-9ae4-21ea1b37d1bf">

**Comment by davidgit** [comment]
Hey @sauharda1,

This environment (EKS) is not currently supported by our prometheus exporter packages.

You'll need to spawn the underlying Prometheus exporter in the cluster and use our Prometheus Agent.

Here are the docs
[https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/#contain[…]onments](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/#containerized-environments)
