### ISSUE TITLE
ibmmq and prometheus exporter

### ISSUE THREAD

**Issue by msilverman1234** [newrelic/newrelic-prometheus-exporters-packages#98]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I'm trying to run ibmmq-nri and am getting a message saying

Jun 14 23:51:33 sufra04selwcllog1001 newrelic-infra-service: time="2022-06-14T23:51:33Z" level=debug msg="Integration stderr (not parsed)." cfg_protocol_name=cfg-nri-ibmmq component=integrations.runner.Runner integration_name=nri-prometheus line="time=\"2022-06-14T23:51:33Z\" level=warning msg=\"error while scraping target\" component=Fetcher error=\"Get \\\"http://localhost:9157/metrics\\\": dial tcp [::1]:9157: connect: connection refused\"" parent_integration_name=nri-ibmmq runner_uid=99287eb533

Following steps in NR docs it is not saying i need to install anything beyond the ibmmq-nri, but nothing is listening on port I'm exposing.

Is there a step I'm missing?  Or are there more logs for ibmmq-nri?

THanks!

Mark

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:  Centos 7

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
